# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsFriendlycaptcha\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  NITSAN\NsFriendlycaptcha\Services\CaptchaService:
    arguments:
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $typoScriptService: '@TYPO3\CMS\Core\TypoScript\TypoScriptService'
      $contentObjectRenderer: '@TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer'
    public: true

